import type { PresData } from "../../types"

// const slid

export const presData: PresData = {
    url: "",
    slideNum: 12,
    quizNum: 1,
    slides: [
        {
            idx: 0,
            name: "green.png",
            kind: "slide",
            questionKind: "",
            quizId: 0,
            width: 600,
            height: 300,
            fontSize: 16,
            question: "",
            vote: [],
            background: "",
            fontColor: "",
            graphColor: "",
        },
        {
            idx: 1,
            name: "example.png",
            kind: "question",
            questionKind: "horizontal",
            question: "Как настроение?",
            quizId: 0,
            width: 600,
            height: 300,
            fontSize: 16,
            vote: [
                {
                    idx: 0,
                    option: "Хорошее",
                    votes: 2,
                    color: "red",
                },
                {
                    idx: 0,
                    option: "Отличное",
                    votes: 5,
                    color: "blue",
                },
            ],
            background: "white",
            fontColor: "#000000",
            graphColor: "#000000",
        },
        {
            idx: 2,
            name: "",
            kind: "slide",
            questionKind: "",
            quizId: 0,
            width: 600,
            height: 300,
            fontSize: 16,
            question: "",
            vote: [],
            background: "",
            fontColor: "",
            graphColor: "",
        },
        {
            idx: 3,
            name: "",
            kind: "slide",
            questionKind: "",
            quizId: 0,
            width: 600,
            height: 300,
            fontSize: 16,
            question: "",
            vote: [],
            background: "",
            fontColor: "",
            graphColor: "",
        },
        {
            idx: 4,
            name: "",
            kind: "slide",
            questionKind: "",
            quizId: 0,
            width: 600,
            height: 300,
            fontSize: 16,
            question: "",
            vote: [],
            background: "",
            fontColor: "",
            graphColor: "",
        },
        {
            idx: 5,
            name: "",
            kind: "slide",
            questionKind: "",
            quizId: 0,
            width: 600,
            height: 300,
            fontSize: 16,
            question: "",
            vote: [],
            background: "",
            fontColor: "",
            graphColor: "",
        },
        {
            idx: 6,
            name: "",
            kind: "slide",
            questionKind: "",
            quizId: 0,
            width: 600,
            height: 300,
            fontSize: 16,
            question: "",
            vote: [],
            background: "",
            fontColor: "",
            graphColor: "",
        },
        {
            idx: 7,
            name: "",
            kind: "slide",
            questionKind: "",
            quizId: 0,
            width: 600,
            height: 300,
            fontSize: 16,
            question: "",
            vote: [],
            background: "",
            fontColor: "",
            graphColor: "",
        },
        {
            idx: 8,
            name: "",
            kind: "slide",
            questionKind: "",
            quizId: 0,
            width: 600,
            height: 300,
            fontSize: 16,
            question: "",
            vote: [],
            background: "",
            fontColor: "",
            graphColor: "",
        },
        {
            idx: 9,
            name: "",
            kind: "slide",
            questionKind: "",
            quizId: 0,
            width: 600,
            height: 300,
            fontSize: 16,
            question: "",
            vote: [],
            background: "",
            fontColor: "",
            graphColor: "",
        },
        {
            idx: 10,
            name: "",
            kind: "slide",
            questionKind: "",
            quizId: 0,
            width: 600,
            height: 300,
            fontSize: 16,
            question: "",
            vote: [],
            background: "",
            fontColor: "",
            graphColor: "",
        },
        {
            idx: 11,
            name: "",
            kind: "slide",
            questionKind: "",
            quizId: 0,
            width: 600,
            height: 300,
            fontSize: 16,
            question: "",
            vote: [],
            background: "",
            fontColor: "",
            graphColor: "",
        },

    ]
}